/** Default discovery district when GPS / query param is unavailable */
export const DEFAULT_DISTRICT = "";

export const SPECIALTIES = [
  { name: "General Physician", id: "General Physician" },
  { name: "Dentist", id: "Dentist" },
  { name: "Dermatologist & Cosmetologist", id: "Dermatologist & Cosmetologist" },
  { name: "Gynecologist & Obstetrician", id: "Gynecologist & Obstetrician" },
  { name: "Pediatrician", id: "Pediatrician" },
  { name: "Orthopedic Surgeon", id: "Orthopedic Surgeon" },
  { name: "ENT Specialist", id: "ENT Specialist" },
  { name: "Ophthalmologist", id: "Ophthalmologist" },
  { name: "Cardiologist", id: "Cardiologist" },
  { name: "Diabetologist", id: "Diabetologist" },
  { name: "Psychiatrist & Psychologist", id: "Psychiatrist & Psychologist" },
  { name: "Physiotherapist", id: "Physiotherapist" },
  { name: "Neurologist", id: "Neurologist" },
  { name: "Gastroenterologist", id: "Gastroenterologist" },
  { name: "Urologist", id: "Urologist" },
  { name: "Pulmonologist", id: "Pulmonologist" },
  { name: "Endocrinologist", id: "Endocrinologist" },
  { name: "Nephrologist", id: "Nephrologist" },
  { name: "Oncologist", id: "Oncologist" },
  { name: "Rheumatologist", id: "Rheumatologist" },
  { name: "Dietitian & Nutritionist", id: "Dietitian & Nutritionist" },
  { name: "Sexologist", id: "Sexologist" },
  { name: "Hair & Skin Specialist", id: "Hair & Skin Specialist" },
  { name: "Ayurvedic Doctor", id: "Ayurvedic Doctor" },
  { name: "Homeopathic Doctor", id: "Homeopathic Doctor" },
  { name: "Unani Specialist", id: "Unani Specialist" },
  { name: "Siddha Specialist", id: "Siddha Specialist" },
  { name: "Naturopath", id: "Naturopath" },
  { name: "Geriatrician", id: "Geriatrician" },
  { name: "Emergency Medicine Specialist", id: "Emergency Medicine Specialist" }
];
